# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    packages:
      - libv8-dev
r_github_packages:
  - mrc-ide/dde
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
