## Automatically generated by odin 1.1.8 - do not edit
deterministic_apothecary_SEIR_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "deterministic_apothecary_SEIR_rhs_dde",
      rhs_desolve = "deterministic_apothecary_SEIR_rhs_desolve",
      initmod_desolve = "deterministic_apothecary_SEIR_initmod_desolve",
      output_dde = "deterministic_apothecary_SEIR_output_dde"),
    dll = "apothecary",
    user = c("beta_set", "D_Community_0", "D_Hospital_0",
             "drug_1_effect_size", "drug_1_indic",
             "drug_10_GetOx_GetMV_effect_size",
             "drug_10_GetOx_NoMV_effect_size",
             "drug_10_indic_ICrit_GetICU_GetOx_GetMV",
             "drug_10_indic_ICrit_GetICU_GetOx_NoMV",
             "drug_10_indic_ICrit_GetICU_NoOx_NoMV",
             "drug_10_NoOx_NoMV_effect_size", "drug_10_prop_treat",
             "drug_11_GetOx_effect_size", "drug_11_indic_IMod_GetHosp_GetOx",
             "drug_11_indic_IMod_GetHosp_NoOx", "drug_11_NoOx_effect_size",
             "drug_11_prop_treat", "drug_12_GetOx_effect_size",
             "drug_12_indic_ISev_GetICU_GetOx",
             "drug_12_indic_ISev_GetICU_NoOx", "drug_12_NoOx_effect_size",
             "drug_12_prop_treat", "drug_13_GetOx_GetMV_effect_size",
             "drug_13_GetOx_NoMV_effect_size",
             "drug_13_indic_ICrit_GetICU_GetOx_GetMV",
             "drug_13_indic_ICrit_GetICU_GetOx_NoMV",
             "drug_13_indic_ICrit_GetICU_NoOx_NoMV",
             "drug_13_NoOx_NoMV_effect_size", "drug_13_prop_treat",
             "drug_2_effect_size_IPreAsymp", "drug_2_effect_size_IPreCase",
             "drug_2_effect_size_IPreMild", "drug_2_indic_IPreAsymp",
             "drug_2_indic_IPreCase", "drug_2_indic_IPreMild",
             "drug_2_prop_treat", "drug_3_effect_size", "drug_3_indic",
             "drug_3_prop_treat", "drug_4_effect_size_IAsymp",
             "drug_4_effect_size_ICase", "drug_4_effect_size_IMild",
             "drug_4_indic_IAsymp", "drug_4_indic_ICase",
             "drug_4_indic_IMild", "drug_4_prop_treat", "drug_5_effect_size",
             "drug_5_indic_ICase", "drug_5_indic_IMild", "drug_5_prop_treat",
             "drug_6_effect_size", "drug_6_indic", "drug_6_prop_treat",
             "drug_7_effect_size", "drug_7_indic", "drug_7_prop_treat",
             "drug_8_GetOx_effect_size", "drug_8_indic_IMod_GetHosp_GetOx",
             "drug_8_indic_IMod_GetHosp_NoOx", "drug_8_NoOx_effect_size",
             "drug_8_prop_treat", "drug_9_GetOx_effect_size",
             "drug_9_indic_ISev_GetICU_GetOx",
             "drug_9_indic_ISev_GetICU_NoOx", "drug_9_NoOx_effect_size",
             "drug_9_prop_treat", "E1_0", "E2_0", "gamma_E", "gamma_IAsymp",
             "gamma_ICase", "gamma_ICrit_GetICU_GetOx_GetMV_Die",
             "gamma_ICrit_GetICU_GetOx_GetMV_Surv",
             "gamma_ICrit_GetICU_GetOx_NoMV_Die",
             "gamma_ICrit_GetICU_GetOx_NoMV_Surv",
             "gamma_ICrit_GetICU_NoOx_NoMV_Die",
             "gamma_ICrit_GetICU_NoOx_NoMV_Surv",
             "gamma_ICrit_NoICU_NoOx_NoMV_Die",
             "gamma_ICrit_NoICU_NoOx_NoMV_Surv", "gamma_IMild",
             "gamma_IMod_GetHosp_GetOx_Die", "gamma_IMod_GetHosp_GetOx_Surv",
             "gamma_IMod_GetHosp_NoOx_Die", "gamma_IMod_GetHosp_NoOx_Surv",
             "gamma_IMod_NoHosp_NoOx_Die", "gamma_IMod_NoHosp_NoOx_Surv",
             "gamma_IPreAsymp", "gamma_IPreCase", "gamma_IPreMild",
             "gamma_ISev_GetICU_GetOx_Die", "gamma_ISev_GetICU_GetOx_Surv",
             "gamma_ISev_GetICU_NoOx_Die", "gamma_ISev_GetICU_NoOx_Surv",
             "gamma_ISev_NoICU_NoOx_Die", "gamma_ISev_NoICU_NoOx_Surv",
             "gamma_rec", "hosp_bed_capacity", "IAsymp_0", "ICase1_0",
             "ICase1Drug3_0", "ICase2_0", "ICase2Drug3_0",
             "ICrit_GetICU_GetOx_GetMV_Die1_0",
             "ICrit_GetICU_GetOx_GetMV_Die2_0",
             "ICrit_GetICU_GetOx_GetMV_Surv1_0",
             "ICrit_GetICU_GetOx_GetMV_Surv2_0",
             "ICrit_GetICU_GetOx_NoMV_Die1_0",
             "ICrit_GetICU_GetOx_NoMV_Die2_0",
             "ICrit_GetICU_GetOx_NoMV_Surv1_0",
             "ICrit_GetICU_GetOx_NoMV_Surv2_0",
             "ICrit_GetICU_NoOx_NoMV_Die1_0",
             "ICrit_GetICU_NoOx_NoMV_Die2_0",
             "ICrit_GetICU_NoOx_NoMV_Surv1_0",
             "ICrit_GetICU_NoOx_NoMV_Surv2_0",
             "ICrit_NoICU_NoOx_NoMV_Die1_0", "ICrit_NoICU_NoOx_NoMV_Die2_0",
             "ICrit_NoICU_NoOx_NoMV_Surv1_0",
             "ICrit_NoICU_NoOx_NoMV_Surv2_0", "ICU_bed_capacity", "IMild_0",
             "IMod_GetHosp_GetOx_Die1_0", "IMod_GetHosp_GetOx_Die2_0",
             "IMod_GetHosp_GetOx_Surv1_0", "IMod_GetHosp_GetOx_Surv2_0",
             "IMod_GetHosp_NoOx_Die1_0", "IMod_GetHosp_NoOx_Die2_0",
             "IMod_GetHosp_NoOx_Surv1_0", "IMod_GetHosp_NoOx_Surv2_0",
             "IMod_NoHosp_NoOx_Die1_0", "IMod_NoHosp_NoOx_Die2_0",
             "IMod_NoHosp_NoOx_Surv1_0", "IMod_NoHosp_NoOx_Surv2_0",
             "IPre1Asymp_0", "IPre1Case_0", "IPre1CaseDrug3_0",
             "IPre1Mild_0", "IPre2Asymp_0", "IPre2Case_0",
             "IPre2CaseDrug3_0", "IPre2Mild_0", "IRec1_0", "IRec2_0",
             "ISev_GetICU_GetOx_Die1_0", "ISev_GetICU_GetOx_Die2_0",
             "ISev_GetICU_GetOx_Surv1_0", "ISev_GetICU_GetOx_Surv2_0",
             "ISev_GetICU_NoOx_Die1_0", "ISev_GetICU_NoOx_Die2_0",
             "ISev_GetICU_NoOx_Surv1_0", "ISev_GetICU_NoOx_Surv2_0",
             "ISev_NoICU_NoOx_Die1_0", "ISev_NoICU_NoOx_Die2_0",
             "ISev_NoICU_NoOx_Surv1_0", "ISev_NoICU_NoOx_Surv2_0",
             "mix_mat_set", "MV_capacity", "N_age", "PE1_0", "PE2_0",
             "prob_asymp", "prob_critical",
             "prob_critical_death_get_ICU_get_ox_get_MV_baseline",
             "prob_critical_death_get_ICU_get_ox_no_MV_baseline",
             "prob_critical_death_get_ICU_no_ox_no_MV_baseline",
             "prob_critical_death_no_ICU_no_ox_no_MV", "prob_hosp",
             "prob_moderate_death_get_hosp_get_ox_baseline",
             "prob_moderate_death_get_hosp_no_ox_baseline",
             "prob_moderate_death_no_hosp_no_ox", "prob_severe",
             "prob_severe_death_get_ICU_get_ox_baseline",
             "prob_severe_death_get_ICU_no_ox_baseline",
             "prob_severe_death_no_ICU_no_ox", "prop_ox_hosp_beds",
             "prop_ox_ICU_beds", "prophylactic_drug_timing_1",
             "prophylactic_drug_timing_2", "prophylactic_drug_wane",
             "prophylactic_prop_treat", "PS_0", "R_0", "rel_inf_asymp",
             "rel_inf_mild", "S_0", "tt_beta", "tt_hosp_beds", "tt_ICU_beds",
             "tt_matrix", "tt_prop_ox_hosp_beds", "tt_prop_ox_ICU_beds"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("deterministic_apothecary_SEIR_rhs_dde", package = "apothecary")
        .C("deterministic_apothecary_SEIR_rhs_desolve", package = "apothecary")
        .C("deterministic_apothecary_SEIR_initmod_desolve", package = "apothecary")
        .C("deterministic_apothecary_SEIR_output_dde", package = "apothecary")
      }
    },

    ## This only does something in delay models
    set_initial = function(t, y, use_dde) {
      .Call("deterministic_apothecary_SEIR_set_initial", private$ptr, t, y, use_dde,
            PACKAGE= "apothecary")
    },

    update_metadata = function() {
      meta <- .Call("deterministic_apothecary_SEIR_metadata", private$ptr,
                    PACKAGE = "apothecary")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, FALSE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("deterministic_apothecary_SEIR_create", user, PACKAGE = "apothecary")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/deterministic_apothecary_SEIR.json", mustWork = TRUE,
                             package = "apothecary")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("deterministic_apothecary_SEIR_set_user", private$ptr, user, PACKAGE = "apothecary")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(t) {
      .Call("deterministic_apothecary_SEIR_initial_conditions", private$ptr, t, PACKAGE = "apothecary")
    },

    rhs = function(t, y) {
      .Call("deterministic_apothecary_SEIR_rhs_r", private$ptr, t, y, PACKAGE = "apothecary")
    },

    deriv = function(t, y) {
      self$rhs(t, y)
    },

    contents = function() {
      .Call("deterministic_apothecary_SEIR_contents", private$ptr, PACKAGE = "apothecary")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_ode(
        self, private, t, y, ..., use_names = use_names)
    }
  ))


deterministic_apothecary_SEIR <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  deterministic_apothecary_SEIR_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(deterministic_apothecary_SEIR) <- "odin_generator"
attr(deterministic_apothecary_SEIR, "generator") <- deterministic_apothecary_SEIR_
